name: "Chromatic"

on: ["push", "pull_request"]

jobs:
  chromatic-deployment:
    if: github.repository_owner == 'codeforboston'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup-repo
      - name: Publish to Chromatic
        uses: chromaui/action@c93e0bc3a63aa176e14a75b61a31847cbfdd341c # v11.27.0
        with:
          projectToken: f8618e690599
          exitZeroOnChanges: true
          exitOnceUploaded: true
