name: Deploy the frontend and backend to the Firebase Production environment.
on:
  push:
    branches:
      - prod

jobs:
  build_and_deploy:
    # Don't deploy forks, even if actions are enabled
    if: github.repository_owner == 'codeforboston'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout Code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Setup Build Environment
        uses: ./.github/actions/setup-repo
      - name: Build and Deploy to Firebase
        uses: w9jds/firebase-action@5bb36bbfc9a346fd7e8826b7209f2d201f085af0 # v13.18.0
        with:
          args: deploy --force --only firestore,functions:maple,storage
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          ASSEMBLY_API_KEY: ${{ secrets.ASSEMBLY_API_KEY }}
          PROJECT_ID: digital-testimony-prod
